version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/tomcat/shoppingcart/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/configure_application.sh
      timeout: 90
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      timeout: 30
